### ISSUE TITLE
Swell page content doesn't get fetched

### ISSUE THREAD

**Issue by wlaj** [vercel/commerce#637] opened 2022-01-08 13:02 UTC
Steps to reproduce

1. Use the following fields in .env.local
```
# Available providers: local, bigcommerce, shopify, swell, saleor, spree, ordercloud, vendure, kibocommerce, commercejs
COMMERCE_PROVIDER=swell

SWELL_STORE_DOMAIN=
SWELL_STOREFRONT_ACCESS_TOKEN=

NEXT_PUBLIC_SWELL_STORE_ID=
NEXT_PUBLIC_SWELL_PUBLIC_KEY=
```

2. Configure 'commerce.config.json' as the following
![Code_HQvVRFcZDf](https://user-images.githubusercontent.com/40787982/148644783-bed58679-3ecc-4efd-80e2-6c3b0bca33bb.png)

3. Configure project and run project locally
`npm i && npx next dev`

4. Fill swell storefront pages with content
![chrome_OcUzfbjNPz](https://user-images.githubusercontent.com/40787982/148645254-b9a4ef10-31b6-4d29-b01d-b7a08ec4babc.png)

5. See page content not being fetched for pages in footer, swell demo has same issue
![chrome_6NRXV3dE4D](https://user-images.githubusercontent.com/40787982/148644985-1db5169a-9308-49a0-94cc-436e32c2bb66.png)

**Comment by charkour** [comment] 2022-01-10 00:09
Hey, swell does not support wishlists out-of-the-box. Here are [their docs](https://developers.swell.is/).

**Comment by Skenja** [comment] 2022-11-16 14:06
Ran into the same problem myself. The problem is not fetching the data, but the lack of normalization - Swell pages are comprised of `sections`, which need to be somehow mapped to HTML that can be stored inside of `body` property.

**Comment by leerob** [comment] 2023-04-18 02:42
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

**Closed by leerob** 2023-04-18 02:42 UTC
