### ISSUE TITLE
[SHOPIFY] update image when variant changes

### ISSUE THREAD

**Issue by GodwinEbikwo** [vercel/commerce#718] opened 2022-03-19 17:51 UTC
Hi, currently changing variants in this shop I am building and the image does not reflect the chosen variant. Any help on how to. move forward.
Thanks

**Comment by okbel** [comment] 2022-03-23 15:35
This in our roadmap and it's currently under progress.

**Comment by GodwinEbikwo** [comment] 2022-03-23 15:50
Cheers for the feedback

**Comment by drugan** [comment] 2022-07-24 18:35
Is not this issue a duplicate of the #22

**Comment by leerob** [comment] 2023-04-18 02:41
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

**Closed by leerob** 2023-04-18 02:41 UTC
Labels: enhancement, in-progress
