### ISSUE TITLE
Provider: Commerce.js

### ISSUE THREAD

**Issue by sarvarrose** [vercel/commerce#406] opened 2021-07-01 06:37 UTC
Ecommerce Provider: https://commercejs.com/

**Comment by robbieaverill** [comment] 2022-01-14 21:45
Duplicate of https://github.com/vercel/commerce/issues/193

**Comment by leerob** [comment] 2023-04-18 02:47
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

**Closed by leerob** 2023-04-18 02:47 UTC
