### ISSUE TITLE
Provider: WooCommerce

### ISSUE THREAD

**Issue by flyboarder** [vercel/commerce#480] opened 2021-09-12 15:16 UTC
It would be great if woocommerce was one of the supported providers.

**Comment by ramyareye** [comment] 2021-09-18 23:07
I did a very first version here: https://commerce-mvjc07mzq-woocommerce.vercel.app/ 
base on [wp-graphql](https://github.com/wp-graphql/wp-graphql) and [wp-graphql-woocommerce](https://github.com/wp-graphql/wp-graphql-woocommerce)

by the next weekend I may can complete all the functionality

**Comment by fabianmarz** [comment] 2021-09-21 08:03
Duplicate of #172. @ramyareye, could you please also share your progress there? :-)

**Comment by geniti** [comment] 2021-09-23 11:14
> I did a very first version here: https://commerce-mvjc07mzq-woocommerce.vercel.app/
> base on [wp-graphql](https://github.com/wp-graphql/wp-graphql) and [wp-graphql-woocommerce](https://github.com/wp-graphql/wp-graphql-woocommerce)
> 
> by the next weekend I may can complete all the functionality
Could you please share some of the steps need to be made?

**Comment by geniti** [comment] 2021-09-24 14:25
@ramyareye are you planning to launch this with all functionality?

**Comment by leerob** [comment] 2023-04-18 02:46
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

**Closed by leerob** 2023-04-18 02:46 UTC

**Comment by hemangjoshi37a** [comment] 2024-09-25 06:16
any update on this ? any new alternative available for woo-commerce to integrate  with this ?
