### ISSUE TITLE
Cannot destructure property 'tree' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by MzDuc2001** [vercel/commerce#1007] opened 2023-05-08 10:12 UTC
I just run npm run dev and I got this error, help me please

error unhandledRejection: Error [TypeError]: Cannot destructure property 'tree' of 'undefined' as it is undefined.
    at MetadataTree (webpack-internal:///(sc_client)/./node_modules/next/dist/esm/lib/metadata/metadata.js:19:31)
    at describeNativeComponentFrame (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:6534:7)
    at describeFunctionComponentFrame (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:6629:12)
    at getStackByComponentStackNode (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8286:19)
    at getCurrentStackInDEV (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8472:12)
    at renderNodeDestructive (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9133:129)
    at renderIndeterminateComponent (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8810:7)
    at renderElement (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8991:7)
    at renderNodeDestructiveImpl (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9157:11)
    at renderNodeDestructive (webpack-internal:///(sc_client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:9129:14) {
  digest: undefined
}

**Comment by leerob** [comment] 2023-05-09 05:03
Did you follow the README to set up your Shopify store as described?

**Comment by MzDuc2001** [comment] 2023-05-09 10:39
Yes sir , i did it all



Have a nice day !
-----------------------
Full name: PHẠM MINH ĐỨC
Phone: 0366176901
-----------------------

Vào 16:11, Th 3, 9 thg 5, 2023 Lee Robinson ***@***.***> đã
viết:

**Comment by manovotny** [comment] 2023-06-06 19:23
@MzDuc2001 this is going to be tricky to root cause as we've never seen this issue ourselves, nor has it been reported by anyone else.

The only think I can think of is to run `npx --no-install next info` and copy / paste it here to see if anything jumps out at us.

**Comment by mein-beer-hu** [comment] 2023-06-16 18:32
Hi Folks, I am trying to setup Spree backend with NextJS storefront, I see the same error popup after I bootstrapped the project. Any pointers on what setup we might be missing?

I bootstrapped the project with Spree's installation guide.

I ran the above command and here is the output

```
npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.2.0
      npm: 9.6.6
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3

warn  - Latest canary version not detected, detected: "13.4.4", newest: "13.4.7-canary.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
```

**Comment by mattbrailsford** [comment] 2023-07-13 19:01
Installing the newest canary as per the warning comment in @mein-beer-hu  output fixed this for me

**Comment by leerob** [comment] 2023-07-19 02:25
Thanks for following up @mattbrailsford! Closing as fixed.

**Closed by leerob** 2023-07-19 02:25 UTC
