### ISSUE TITLE
Problems with carousel! Please anyone can help me?

### ISSUE THREAD

**Issue by maxinelobato** [vercel/commerce#1001] opened 2023-04-28 18:55 UTC
Hello everyone, how are you doing? I'm new to Shopify and I'm having some difficulty setting up the carousel on the homepage of my e-commerce store. If anyone could help me, I would be truly grateful!

**Comment by leerob** [comment] 2023-05-01 02:35
Can you be more specific what the issue is why the carousel in this template? 🙏

**Comment by leerob** [comment] 2023-05-09 05:02
Closing out, but happy to revisit.

**Closed by leerob** 2023-05-09 05:02 UTC
