### ISSUE TITLE
SyntaxError: Unexpected token '?' from < iOS 14

### ISSUE THREAD

**Issue by leeuwisarvin** [vercel/commerce#750] opened 2022-05-11 10:02 UTC
I was doing some testing on a iOS 13 device (Safari) and it threw some errors. The one who causes this was this line:

```SyntaxError: Unexpected token '?'```

It appears in the usePrice function and throughout other functions. Also, it does appear when testing the demo site on that same device. Does anyone know how to fix this?

**Comment by shixin-guo** [comment] 2022-05-29 08:45
+ 1

**Comment by shixin-guo** [comment] 2022-05-29 08:57
https://nextjs.org/docs/basic-features/supported-browsers-features

![image](https://user-images.githubusercontent.com/12186221/170860250-1c3c2fc3-f2a1-4632-9fa1-8461f7582d18.png)
![image](https://user-images.githubusercontent.com/12186221/170860258-cb4b2dd3-957e-429a-a732-3450b2e6fb0e.png)

**Comment by EchoZhaoH** [comment] 2022-08-07 07:18
<img width="1936" alt="image" src="https://user-images.githubusercontent.com/23427655/183279808-0e21f44c-29da-4d69-a2e3-03f04928eeec.png">
default option value is the root cause

**Comment by EchoZhaoH** [comment] 2022-08-07 07:20
need to change the target to a lower es version in the tsconfig file and set the server option to false
![image](https://user-images.githubusercontent.com/23427655/183279865-2753b8f3-ff3a-4745-a92e-83cb0ca1a600.png)
![image](https://user-images.githubusercontent.com/23427655/183279868-8cf66d21-c658-4cd2-a780-9fc2d7d39825.png)

**Comment by leerob** [comment] 2023-04-18 02:39
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

**Closed by leerob** 2023-04-18 02:39 UTC
