### ISSUE TITLE
[BUG]logout not working in demo site

### ISSUE THREAD

**Issue by ahmadsyed** [vercel/commerce#229] opened 2021-03-12 16:12 UTC
Hi, 

I noticed in my deployed site that if a customer clicks log out, and then refreshes the page, he gets login again. Also, I Confirmed the same on the Demo site and saw the same bug present over there also. 
It's only happening in Deployed sites, on the local cookie is getting deleted fine.
Is everyone else seeing the same in their installations?

**Comment by lfades** [comment] 2021-03-12 23:28
I can't reproduce this bug 🤔 . Are you on the bigcommerce demo or the shopify demo?

**Comment by ahmadsyed** [comment] 2021-03-19 21:23
Hi, Thanks for the reply. I am working with bigcommerce. Here is the URL [https://demo.vercel.store/]. Please try to replicate here.

**Comment by ahmadsyed** [comment] 2021-03-23 10:52
Hi, @lfades 
Do we have any updates on this bug. or any workaround, for now, would be much help full.

**Comment by lfades** [comment] 2021-03-23 23:01
@ahmadsyed I'll take a look tomorrow 👍

**Comment by ryanford** [comment] 2021-08-31 18:29
I tried to fix the Commerce code, but it's a little too abstracted for me to follow. For whatever reason the function returned from  `useLogout` does not appear to be touching the `SHOPPER_TOKEN` cookie at all. I ended up creating a new API route in next using similar logic:
```js
// pages/api/customer/logout.ts
// this has to come from the server/API side as it's an HTTP only cookie
import { serialize } from 'cookie'

export default async function handler(_, res) {
  res.setHeader(
    'Set-Cookie',
    serialize('SHOP_TOKEN', '', { expires: new Date(0), path: '/' })
  )
  res.setHeader(
    'Set-Cookie',
    serialize('Shopper-Pref', '', { expires: new Date(0), path: '/' })
  )

  return res.status(200).json({ message: 'logged out successfully' })
}
```
Then I hit this from the client-side when I need to logout.
```jsx
import { useRouter } from 'next/router'
const router = useRouter()
...
return (
  <button
    onClick={async () => {
      await fetch('/api/customers/logout')
      router.reload()
    }}
  >Logout</button>
)
```
Hope this helps future readers while the Vercel team figures something out with the Commerce API.

**Comment by emanuel-imaginationmedia** [comment] 2022-09-14 20:39
I don't know why, but I think this problem is related to the HTTP method. I modified from GET to POST and it worked.

**Comment by manovotny** [comment] 2023-04-18 02:45
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966

**Closed by manovotny** 2023-04-18 02:45 UTC
Labels: bug
