### ISSUE TITLE
[BUG] log in and Sign Up always return error

### ISSUE THREAD

**Issue by buty619** [vercel/commerce#26] opened 2020-10-28 02:16 UTC
### For Sign Up
* on local and in the deployed page when I try to make a sing up always get `An unexpected error ocurred` and the logs says `Error: Internal server error at FetcherError.CommerceError [as constructor]` but then in the `mybigcommerce` i can see the user created as expected

### For Log In

* on local and in the deployed page  always return `An unexpected error ocurred. Did you forgot your password?` and the logs says `Error: Internal server error at FetcherError.CommerceError [as constructor]`

**Comment by okbel** [comment] 2020-10-28 13:50
Did you set the env vars right? We just merged .env.template. LMK!

**Comment by buty619** [comment] 2020-10-28 17:19
yes i set it whit the vercel shell and making `vercel env pull` but is set as usual .env, so i don't have the error asking for the env vars on my local, also @okbel  thanks for answering ¡¡

**Comment by robbieaverill** [comment] 2020-10-29 16:48
I just noticed this on demo.vercel.store too - is the login API supposed to return a 500 when I put an invalid username/password in? Seems like a 40x would be better.

**Comment by okbel** [comment] 2020-11-03 19:45
Bringing BigCommerce to debug this @RayeEThompson

**Comment by Balance8** [comment] 2020-11-04 05:40
I can corroborate that I am experiencing the same issue, env variables pulled via vercel CLI, account created according to the regex.  ```Error: Internal server error
    at FetcherError.CommerceError [as constructor]```
User is generated in big commerce 

![image](https://user-images.githubusercontent.com/36809369/98073351-031c4000-1e1d-11eb-942f-63aeb68fa3c7.png)

**Comment by magicspon** [comment] 2020-11-04 13:22
Snap... I'm also seeng this error.

**Comment by RayeEThompson** [comment] 2020-11-04 14:21
Hey guys, working with the team to debug this. We have the issue reported to BigCommerce engineering. I will follow up as soon as possible.

**Comment by sadpvndv** [comment] 2020-11-04 16:19
I have this error on SignUp and Login `Error: Invalid credentials at FetcherError.CommerceError [as constructor]` on local and in the deployed page

**Comment by murillo94** [comment] 2020-11-05 00:52
Same error here, tried to login in and sign up takes the error:

|view|url|response|
|-----|--|---------|
|![Captura de Tela 2020-11-04 às 21 48 44](https://user-images.githubusercontent.com/9031279/98183865-d7b25780-1ee7-11eb-8348-84c5e1c0a245.png)|![Captura de Tela 2020-11-04 às 21 48 32](https://user-images.githubusercontent.com/9031279/98183880-dc770b80-1ee7-11eb-93bd-9b579c79386d.png)|![Captura de Tela 2020-11-04 às 21 48 23](https://user-images.githubusercontent.com/9031279/98183889-e1d45600-1ee7-11eb-8df4-46b63579cfb2.png)|

**Comment by RayeEThompson** [comment] 2020-11-30 23:32
To follow up here, I have been investigating and the issue is not on the BigCommerce receiving the requests. It is on the return from the BigCommerce Data-Hooks. Can you all please share your experience with [Storefront-Data-Hooks Issues](https://github.com/bigcommerce/storefront-data-hooks/issues)? 
This will help us immensely and I will create an issue there tomorrow, with all of my research and findings.

**Comment by Tomburgs** [comment] 2020-12-01 17:40
@RayeEThompson is that the case also for login requests?

I attempted to create a new GraphQL API Token through `/v3/storefront/api-token` with all the permissions topped out and then create a custom GraphQL request through postman, but I'm still getting back the `Invalid Credentials` error, even though I've triple-checked that they are correct.

When creating the same request through the Storefront API Playground I get back success. 🙁

**Comment by RayeEThompson** [comment] 2020-12-03 14:06
Please go here and add your comments and feedback for the errors that are captured in this issue:
https://github.com/bigcommerce/storefront-data-hooks/issues/13

**Closed** 2020-12-21 17:27 UTC
Labels: awaiting response
